version: '3.8'

services:
  da-mysqldb:
    image: mysql:9.1
    container_name: da-mysqldb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf # DOUBLE CHECK THE CONF! Mount custom MySQL configuration file
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql # Mount SQL initialization scripts

    environment:
      MYSQL_ROOT_PASSWORD: Wwsdm1dH?
      MYSQL_DATABASE: da-db

    ports:
      - "3306:3306"
    networks:
      - diplomarbeit-at

  da-springapi:
    container_name: da-springapi
    image: sanomc/da-api:1.0
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - da-mysqldb
    environment:
      MYSQL_HOST: da-mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: Wwsdm1dH?
      MYSQL_PORT: 3306
    networks:
      - diplomarbeit-at
networks:
  diplomarbeit-at:
    driver: bridge