version: "3.7"
services:
  da-sprung-backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - diplomarbeit-at
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/da-db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:9.1"
    restart: always
    ports:
      - 3306:3306
    networks:
      - diplomarbeit-at
    environment:
      MYSQL_DATABASE: da-db
      MYSQL_ROOT_PASSWORD: Wwsdm1dH?
networks:
  diplomarbeit-at: